### PR TITLE
Use the TimeInstant metadata when updating a device geolocation

### PR DESCRIPTION
**Pull request by gtorodelvalle**
- 100% tests passed

### CODE REVIEW

**Comment by dmoranj** [comment]
Don't see any tests here. Can you add it to previous tests of the same feature (geolocation)?

**Comment by gtorodelvalle** [comment]
Yeap, this is probably a good time to solve https://github.com/telefonicaid/context-adapter/issues/44 :) Thanks for pointing it out! I'll include them ASAP and I'll ask you for a new revision... ;)

**Comment by gtorodelvalle** [comment]
@dmoranj , unit tests included for the notification of geolocation updates via the `P1` attribute... ;)

**Comment by dmoranj** [comment]
LGTM

**Pull request merged**
